language: java
jdk: openjdk11
before_install:
  - sudo apt install openjfx
  - sudo apt-get install ant-optional
  - sudo yum install ant-junit
dist: xenial
addons:
  apt:
    packages:
      - ant
install: true
script: ant -lib C:\Program Files\apache-ant-1.9.15\lib\ant-unit.jar test